development:
  adapter: async

test:
  adapter: redis
  url: redis://localhost:6379/1

production:
  adapter: redis
  url: redis://redistogo:19593abece71ca75a71a5180793d75df@angelfish.redistogo.com:11339/


